# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Prueba' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Prueba
  pod 'AWSAuthCore', '~> 2.6.1'
  pod 'AWSCognitoIdentityProvider', '~> 2.6.0'
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON'
  pod 'AWSPinpoint'

end
